function buildTVController()
%buildTVController Build the literature-based TV controller model.
%
% Paper basis
% -----------
% L. De Novellis, A. Sorniotti, P. Gruber, and A. Pennycott,
% "Comparison of Feedback Control Techniques for Torque-Vectoring Control
% of Fully Electric Vehicles," IEEE Trans. Veh. Technol., 2014.
%
% Implemented paper features:
%   1. continuous reference-yaw-rate generation and tau = 0.3 s filter;
%   2. quasi-static feedforward yaw moment;
%   3. constant-gain parallel PID yaw-rate feedback;
%   4. actuator saturation and back-calculation anti-windup.
%
% Project adaptations are identified in the model annotations and MATLAB
% Function comments. In particular, path curvature replaces the paper's
% steering/understeer lookup table, and an analytical E-Class bicycle model
% replaces the unavailable quasi-static feedforward lookup tables.

projectRoot = fileparts(fileparts(mfilename("fullpath")));
modelPath = fullfile(projectRoot, "models", "controllers", "TV.slx");
modelName = "TV";

backupPath = fullfile(tempdir, "TV_before_codex_controller.slx");
copyfile(modelPath, backupPath, "f");

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
load_system(modelPath);

deleteRootContents(modelName);
createInterface(modelName);
createReferenceChannel(modelName);
createFeedbackChannel(modelName);
createFeedforwardChannel(modelName);
createMomentOutput(modelName);
createDocumentation(modelName);

set_param(modelName, "Description", ...
    "Adapted De Novellis et al. (IEEE TVT 2014) feedforward + PID TV controller.");
save_system(modelName, modelPath);
close_system(modelName, 0);

fprintf("Built and saved %s\n", modelPath);
fprintf("Pre-edit backup: %s\n", backupPath);
end

function deleteRootContents(modelName)
lineHandles = find_system(modelName, "FindAll", "on", ...
    "SearchDepth", 1, "Type", "line");
for k = 1:numel(lineHandles)
    try
        delete_line(lineHandles(k));
    catch
        % A parent line deletion can invalidate handles for its branches.
    end
end

blocks = find_system(modelName, "SearchDepth", 1, "Type", "block");
for k = 1:numel(blocks)
    delete_block(blocks{k});
end

annotations = find_system(modelName, "FindAll", "on", ...
    "SearchDepth", 1, "Type", "annotation");
for k = 1:numel(annotations)
    delete(annotations(k));
end
end

function createInterface(modelName)
add_block("simulink/Sources/In1", modelName + "/delta_base", ...
    "Port", "1", "Position", [30 55 60 75]);
add_block("simulink/Sources/In1", modelName + "/Ref", ...
    "Port", "2", "OutDataTypeStr", "Bus: ReferenceBus", ...
    "Position", [30 145 60 165]);
add_block("simulink/Sources/In1", modelName + "/VehicleState", ...
    "Port", "3", "OutDataTypeStr", "Bus: VehicleStateBus", ...
    "Position", [30 245 60 265]);

add_block("simulink/Sinks/Out1", modelName + "/delta_add", ...
    "Port", "1", "Position", [1340 55 1370 75]);
add_block("simulink/Sinks/Out1", modelName + "/Mz", ...
    "Port", "2", "Position", [1340 325 1370 345]);

add_block("simulink/Sources/Constant", modelName + "/NoAFSAddition", ...
    "Value", "0", "Position", [1230 50 1260 80]);
connect(modelName, "NoAFSAddition/1", "delta_add/1", "delta_add", false);

% delta_base remains part of the common controller interface. In this
% autonomous-path adaptation it is intentionally not used by TV
% feedforward: unlike the paper's driver steering input, delta_base already
% contains closed-loop path-error correction. Feeding it forward creates
% an unintended interaction between the path and yaw-rate control loops.
add_block("simulink/Sinks/Terminator", modelName + "/DeltaBaseMonitor", ...
    "Position", [105 54 125 76]);
connect(modelName, "delta_base/1", "DeltaBaseMonitor/1", "delta_base", true);

add_block("simulink/Signal Routing/Bus Selector", ...
    modelName + "/ReferenceSignals", ...
    "OutputSignals", "kappa_ref,mu", ...
    "Position", [105 125 110 185]);
add_block("simulink/Signal Routing/Bus Selector", ...
    modelName + "/StateSignals", ...
    "OutputSignals", "Vx,r,beta", ...
    "Position", [105 225 110 305]);

connect(modelName, "Ref/1", "ReferenceSignals/1", "Ref", false);
connect(modelName, "VehicleState/1", "StateSignals/1", "VehicleState", false);

add_block("simulink/Sinks/Terminator", modelName + "/BetaMonitor", ...
    "Position", [255 286 275 304]);
connect(modelName, "StateSignals/3", "BetaMonitor/1", "beta", true);
end

function createReferenceChannel(modelName)
targetPath = modelName + "/YawRateTarget";
add_block("simulink/User-Defined Functions/MATLAB Function", targetPath, ...
    "Position", [190 125 340 205]);

chart = findEMChart(targetPath);
chart.Script = strjoin({ ...
    'function r_target = yawRateTarget(Vx, kappa_ref, mu)', ...
    '%YAWRATETARGET Path-based adaptation of De Novellis Sec. II-D.', ...
    '% The paper uses r_ref,S = ay/V (Eq. 7). For a path with curvature', ...
    '% kappa, ay = Vx^2*kappa, hence r_target = Vx*kappa.', ...
    '%', ...
    '% The paper''s unavailable mu-dependent lookup table is represented', ...
    '% here by the transparent physical bound |Vx*r| <= mu*g.', ...
    'g = 9.81;', ...
    'if abs(Vx) < 0.1', ...
    '    % Numerical domain guard at standstill; inactive in test cases.', ...
    '    r_target = 0;', ...
    '    return;', ...
    'end', ...
    'r_path = Vx*kappa_ref;', ...
    'r_limit = mu*g/abs(Vx);', ...
    'r_target = min(max(r_path, -r_limit), r_limit);', ...
    'end'}, newline);

add_block("simulink/Continuous/Transfer Fcn", ...
    modelName + "/ReferenceFilter", ...
    "Numerator", "1", "Denominator", "[tv.tauRef 1]", ...
    "Position", [390 145 480 185]);
set_param(modelName + "/ReferenceFilter", "Description", ...
    "Paper Sec. II-D: first-order reference-yaw-rate factor, tau = 0.3 s.");

connect(modelName, "ReferenceSignals/1", "YawRateTarget/2", "kappa_ref", false);
connect(modelName, "ReferenceSignals/2", "YawRateTarget/3", "mu", false);
connect(modelName, "StateSignals/1", "YawRateTarget/1", "Vx", false);
connect(modelName, "YawRateTarget/1", "ReferenceFilter/1", "r_target", true);
end

function createFeedbackChannel(modelName)
add_block("simulink/Math Operations/Sum", modelName + "/YawRateError", ...
    "Inputs", "+-", "IconShape", "round", ...
    "Position", [535 145 565 185]);
connect(modelName, "ReferenceFilter/1", "YawRateError/1", "r_ref", true);
connect(modelName, "StateSignals/2", "YawRateError/2", "r", false);
set_param(modelName + "/YawRateError", "Description", ...
    ["e_r = r_ref - r matches negative feedback in paper Eq. (5) and " ...
     "the project plant's convention that positive Mz increases r. The " ...
     "sentence immediately before Eq. (5) prints the opposite order."]);

add_block("simulink/Math Operations/Gain", modelName + "/Kp", ...
    "Gain", "tv.Kp", "Position", [620 105 690 135]);
add_block("simulink/Math Operations/Gain", modelName + "/Ki", ...
    "Gain", "tv.Ki", "Position", [620 165 690 195]);
add_block("simulink/Continuous/Derivative", modelName + "/ErrorDerivative", ...
    "Position", [620 235 655 265]);
add_block("simulink/Math Operations/Gain", modelName + "/Kd", ...
    "Gain", "tv.Kd", "Position", [690 235 760 265]);

add_block("simulink/Math Operations/Sum", modelName + "/IntegratorDrive", ...
    "Inputs", "++", "IconShape", "round", ...
    "Position", [735 155 765 205]);
set_param(modelName + "/IntegratorDrive", "Description", ...
    ["Integral drive = Ki*e_r + Kaw*(Mz-Mz_unsat). The paper states " ...
     "that anti-windup is included but does not publish its realization; " ...
     "the back-calculation topology and tauAw are project choices."]);
add_block("simulink/Continuous/Integrator", modelName + "/ErrorIntegrator", ...
    "InitialCondition", "0", "Position", [805 165 835 195]);

add_block("simulink/Math Operations/Sum", modelName + "/FeedbackMoment", ...
    "Inputs", "+++", "IconShape", "round", ...
    "Position", [900 110 930 270]);

connect(modelName, "YawRateError/1", "Kp/1", "e_r", true);
connect(modelName, "YawRateError/1", "Ki/1", "", false);
connect(modelName, "YawRateError/1", "ErrorDerivative/1", "", false);
connect(modelName, "Ki/1", "IntegratorDrive/1", "Ki_e", false);
connect(modelName, "IntegratorDrive/1", "ErrorIntegrator/1", "integrator_drive", false);
connect(modelName, "ErrorDerivative/1", "Kd/1", "de_r_dt", false);
connect(modelName, "Kp/1", "FeedbackMoment/1", "Mz_P", false);
connect(modelName, "ErrorIntegrator/1", "FeedbackMoment/2", "Mz_I", false);
connect(modelName, "Kd/1", "FeedbackMoment/3", "Mz_D", false);
end

function createFeedforwardChannel(modelName)
ffPath = modelName + "/FeedforwardMoment";
add_block("simulink/User-Defined Functions/MATLAB Function", ffPath, ...
    "Position", [360 360 570 475]);

chart = findEMChart(ffPath);
chart.Script = strjoin({ ...
    'function Mz_ff = feedforwardMoment(kappa_ref, Vx, r_target, p)', ...
    '%FEEDFORWARDMOMENT Analytical replacement for paper lookup tables.', ...
    '% De Novellis Sec. III-A obtains Mz_ff from optimized quasi-static', ...
    '% maps indexed by an exogenous driver steering demand. In this project', ...
    '% the exogenous command is path curvature; delta_base also contains', ...
    '% closed-loop path-error correction and is therefore not equivalent to', ...
    '% the paper''s driver input. Nominal kinematic steering is used instead.', ...
    '%', ...
    '% The unavailable maps are replaced by the same steady-equilibrium', ...
    '% idea evaluated explicitly with the project linear bicycle model.', ...
    'm = p(1); a = p(2); b = p(3); Caf = p(4); Car = p(5);', ...
    'if abs(Vx) < 0.1', ...
    '    Mz_ff = 0;', ...
    '    return;', ...
    'end', ...
    'delta_nom = atan((a+b)*kappa_ref);', ...
    'Vy_ss = (Caf*Vx*delta_nom + (b*Car-a*Caf)*r_target ...', ...
    '         - m*Vx^2*r_target)/(Caf+Car);', ...
    'alpha_f = delta_nom - (Vy_ss+a*r_target)/Vx;', ...
    'alpha_r = -(Vy_ss-b*r_target)/Vx;', ...
    'Fyf_ss = Caf*alpha_f;', ...
    'Fyr_ss = Car*alpha_r;', ...
    '% Enforce steady yaw equilibrium: 0 = a*Fyf-b*Fyr+Mz_ff.', ...
    'Mz_ff = -(a*Fyf_ss-b*Fyr_ss);', ...
    'end'}, newline);

add_block("simulink/Sources/Constant", modelName + "/VehicleParameters", ...
    "Value", "tv.vehicleParams", "Position", [205 425 295 455]);
set_param(modelName + "/VehicleParameters", "Description", ...
    "[m, a, b, Caf, Car] for analytical E-Class feedforward.");

connect(modelName, "ReferenceSignals/1", "FeedforwardMoment/1", "", false);
connect(modelName, "StateSignals/1", "FeedforwardMoment/2", "", false);
connect(modelName, "YawRateTarget/1", "FeedforwardMoment/3", "", false);
connect(modelName, "VehicleParameters/1", "FeedforwardMoment/4", "vehicle_params", false);
end

function createMomentOutput(modelName)
add_block("simulink/Math Operations/Sum", modelName + "/TotalMoment", ...
    "Inputs", "++", "IconShape", "round", ...
    "Position", [990 300 1020 350]);
add_block("simulink/Discontinuities/Saturation", modelName + "/MomentLimit", ...
    "UpperLimit", "tv.MzMax", "LowerLimit", "-tv.MzMax", ...
    "ZeroCross", "off", ...
    "Position", [1080 305 1140 345]);
set_param(modelName + "/MomentLimit", "Description", ...
    ["Fixed bicycle-model yaw-moment authority; replace with plant-specific " ...
     "feasible limits. Zero-crossing detection is disabled only on this " ...
     "hard limiter to prevent event chattering; the top-level harness " ...
     "therefore uses tv.maxSolverStep to resolve the fast control loop."]);

add_block("simulink/Math Operations/Sum", modelName + "/SaturationError", ...
    "Inputs", "+-", "IconShape", "round", ...
    "Position", [1040 415 1070 455]);
add_block("simulink/Math Operations/Gain", modelName + "/Kaw", ...
    "Gain", "tv.Kaw", "Position", [1110 420 1180 450]);
set_param(modelName + "/Kaw", "Description", ...
    ["Project-specific back-calculation gain. The paper confirms " ...
     "anti-windup but does not publish its topology or gain."]);

connect(modelName, "FeedbackMoment/1", "TotalMoment/1", "Mz_fb", true);
connect(modelName, "FeedforwardMoment/1", "TotalMoment/2", "Mz_ff", true);
connect(modelName, "TotalMoment/1", "MomentLimit/1", "Mz_unsat", true);
connect(modelName, "MomentLimit/1", "Mz/1", "Mz", true);
connect(modelName, "MomentLimit/1", "SaturationError/1", "", false);
connect(modelName, "TotalMoment/1", "SaturationError/2", "", false);
connect(modelName, "SaturationError/1", "Kaw/1", "saturation_error", false);
connect(modelName, "Kaw/1", "IntegratorDrive/2", "anti_windup", false);
end

function createDocumentation(modelName)
paperText = strjoin({ ...
    'PAPER BASIS: De Novellis et al., IEEE TVT 63(8), 2014, Sec. II-D, II-E, III-A.', ...
    'Published elements: tau=0.3 s reference filter; feedforward + PID; saturation/anti-windup.', ...
    'Active published 90-km/h gains: Kp=80 kNms/rad, Ki=0.004 Nm/rad, Kd=0.8 Nms^2/rad.', ...
    'Paper requires speed scheduling outside its narrow speed range but does not publish the schedule.', ...
    'Project adaptations: path-curvature reference; analytical E-Class feedforward; fixed Mz limit; back-calculation anti-windup; no wheel allocator.'}, newline);
ann = Simulink.Annotation(modelName, paperText);
ann.Position = [180 15 980 65];
ann.FontSize = 10;

ann = Simulink.Annotation(modelName, ...
    "Reference yaw rate (paper Eq. 7 + tau = 0.3 s filter)");
ann.Position = [180 90 480 110];
ann.FontWeight = "bold";

ann = Simulink.Annotation(modelName, ...
    "Parallel PID feedback with explicit back-calculation anti-windup");
ann.Position = [600 75 960 95];
ann.FontWeight = "bold";

ann = Simulink.Annotation(modelName, ...
    "Quasi-static E-Class feedforward adaptation");
ann.Position = [350 330 650 350];
ann.FontWeight = "bold";
end

function chart = findEMChart(blockPath)
root = sfroot;
chart = root.find("-isa", "Stateflow.EMChart", "Path", blockPath);
if isempty(chart)
    error("buildTVController:ChartNotFound", ...
        "Could not locate MATLAB Function chart at %s.", blockPath);
end
chart = chart(1);
end

function lineHandle = connect(modelName, source, destination, signalName, logSignal)
lineHandle = add_line(modelName, source, destination, "autorouting", "on");
if strlength(signalName) > 0
    try
        set_param(lineHandle, "Name", signalName);
    catch exception
        % Bus Selector outputs already carry propagated element labels
        % (for example, <beta>) and Simulink prohibits overriding them.
        % Preserve that informative propagated name, but rethrow unrelated
        % signal-naming failures so the builder cannot hide real defects.
        if ~contains(exception.message, "Bus Selector")
            rethrow(exception);
        end
    end
end
if logSignal
    try
        set_param(lineHandle, "DataLogging", "on");
    catch exception
        % Some propagated bus-element lines do not expose DataLogging as a
        % line parameter. Those elements remain available through the
        % logged VehicleState/Reference buses in the experiment harness.
        if ~contains(exception.message, "DataLogging")
            rethrow(exception);
        end
    end
end
end
